### ISSUE TITLE
server engineTopic undefined.undefined

### ISSUE THREAD

**Issue by theseusyang** [bitloops/bitloops-workflow#25]
server engineTopic undefined.undefined
(node:77196) UnhandledPromiseRejectionWarning: NatsError: BAD_SUBJECT
    at Function.errorForCode (/Users/theseusyang/Dev/bitloops/bitloops-engine/node_modules/nats/lib/nats-base-client/error.js:98:16)
    at NatsConnectionImpl._check (/Users/theseusyang/Dev/bitloops/bitloops-engine/node_modules/nats/lib/nats-base-client/nats.js:104:37)
    at NatsConnectionImpl.subscribe (/Users/theseusyang/Dev/bitloops/bitloops-engine/node_modules/nats/lib/nats-base-client/nats.js:116:14)
    at NATS.<anonymous> (/Users/theseusyang/Dev/bitloops/bitloops-engine/dist/services/NATS.js:122:33)
    at Generator.next (<anonymous>)
    at /Users/theseusyang/Dev/bitloops/bitloops-engine/dist/services/NATS.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/theseusyang/Dev/bitloops/bitloops-engine/dist/services/NATS.js:4:12)
    at NATS.subscribe (/Users/theseusyang/Dev/bitloops/bitloops-engine/dist/services/NATS.js:104:16)
    at /Users/theseusyang/Dev/bitloops/bitloops-engine/dist/server.js:93:8
(Use `node --trace-warnings ...` to show where the warning was created)
(node:77196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:77196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by danias** [comment]
Thanks again the same issue with missing .env parameters. We will add checks so that the server doesn't start if these are missing. You need to define the topics in .env.dev and start the engine with yarn start:dev
